1. SELECT MAX(SALARY) FROM EMPLOYEE;
2. SELECT DEPARTMENT_ID FROM EMPLOYEE WHERE SALARY = MAX(SALARY) FROM EMPLOYEE;
3. WITH DEP_SALARY AS (SELECT DEPARTMENT_ID, SUM(SALARY) AS SALARY FROM EMPLOYEE)
    SELECT DEPARTMENT_ID FROM DEP_SALARY WHERE DEP_SALARY.SALARY = (SELECT MAX(SALARY) FROM DEP_SALARY);
4. SELECT * FROM EMPLOYEE WHERE NAME LIKE '%Р' AND NAME LIKE '%н';